{
    "swagger": "2.0", 
    "info": {
        "version": "v1", 
        "title": "Draft swagger file for Fujitsu K5 Portal User API", 
        "x-service": "k5-apiportal", 
        "x-scope": "portal"
    }, 
    "host": "k5-apiportal.paas.cloud.global.fujitsu.com", 
    "schemes": [
        "https"
    ], 
    "securityDefinitions": {
        "auth_portal": {
            "type": "apiKey", 
            "name": "X-Auth-Token", 
            "in": "header"
        }
    }, 
    "security": [
        {
            "auth_portal": []
        }
    ], 
    "definitions": {
        "putUserspassword": {
            "type": "object", 
            "example": {
                "application/json": {
                    "before_password": "Abcdefgh12345678", 
                    "login_id": "fujitsu123", 
                    "after_password": "Newpassword12345678"
                }
            }, 
            "properties": {
                "before_password": {
                    "type": "string"
                }, 
                "login_id": {
                    "type": "string"
                }, 
                "after_password": {
                    "type": "string"
                }
            }
        }, 
        "putUsers": {
            "type": "object", 
            "example": {
                "application/json": {
                    "login_id": "fujitsu123", 
                    "user_status": "1", 
                    "user_description": "User description.", 
                    "user_first_name": "John", 
                    "user_last_name": "Smith", 
                    "language_code": "ja", 
                    "password": "Abcdefgh12345678", 
                    "mailaddress": "abc@xyz.com"
                }
            }, 
            "properties": {
                "login_id": {
                    "type": "string"
                }, 
                "user_status": {
                    "type": "string"
                }, 
                "user_description": {
                    "type": "string"
                }, 
                "user_first_name": {
                    "type": "string"
                }, 
                "user_last_name": {
                    "type": "string"
                }, 
                "language_code": {
                    "type": "string"
                }, 
                "password": {
                    "type": "string"
                }, 
                "mailaddress": {
                    "type": "string"
                }
            }
        }, 
        "postUsers": {
            "type": "object", 
            "example": {
                "application/json": {
                    "login_id": "fujitsu123", 
                    "user_status": "1", 
                    "user_description": "User description", 
                    "user_first_name": "John", 
                    "role_code": "00", 
                    "user_last_name": "Smith", 
                    "language_code": "ja", 
                    "password": "Abcdefgh12345678", 
                    "mailaddress": "abc@xyz.com"
                }
            }, 
            "properties": {
                "login_id": {
                    "type": "string"
                }, 
                "user_status": {
                    "type": "string"
                }, 
                "user_description": {
                    "type": "string"
                }, 
                "user_first_name": {
                    "type": "string"
                }, 
                "role_code": {
                    "type": "string"
                }, 
                "user_last_name": {
                    "type": "string"
                }, 
                "language_code": {
                    "type": "string"
                }, 
                "password": {
                    "type": "string"
                }, 
                "mailaddress": {
                    "type": "string"
                }
            }
        }
    }, 
    "paths": {
        "/API/v1/api/users": {
            "put": {
                "produces": [
                    "application/json"
                ], 
                "consumes": [
                    "application/json"
                ], 
                "responses": {
                    "200": {
                        "description": "200 response", 
                        "examples": {
                            "application/json": {
                                "login_id": "fujitsu123", 
                                "user_status": "1", 
                                "user_description": "User description.", 
                                "user_first_name": "John", 
                                "user_last_name": "Smith", 
                                "language_code": "ja", 
                                "mailaddress": "abc@xyz.com"
                            }
                        }
                    }
                }, 
                "parameters": [
                    {
                        "schema": {
                            "$ref": "#/definitions/putUsers"
                        }, 
                        "required": false, 
                        "name": "body", 
                        "in": "body"
                    }
                ], 
                "summary": "Change user information"
            }, 
            "post": {
                "produces": [
                    "application/json"
                ], 
                "consumes": [
                    "application/json"
                ], 
                "responses": {
                    "200": {
                        "description": "200 response", 
                        "examples": {
                            "application/json": {
                                "login_id": "fujitsu123", 
                                "authentication_method ": "0", 
                                "user_status": "1", 
                                "user_description": "User description.", 
                                "user_first_name": "John", 
                                "user_last_name": "Smith", 
                                "language_code": "ja", 
                                "mailaddress": "abc@xyz.com"
                            }
                        }
                    }
                }, 
                "parameters": [
                    {
                        "schema": {
                            "$ref": "#/definitions/postUsers"
                        }, 
                        "required": false, 
                        "name": "body", 
                        "in": "body"
                    }
                ], 
                "summary": "Create new user"
            }
        }, 
        "/API/v1/api/userspassword": {
            "put": {
                "consumes": [
                    "application/json"
                ], 
                "responses": {
                    "200": {
                        "description": "200 response", 
                        "examples": {}
                    }
                }, 
                "parameters": [
                    {
                        "schema": {
                            "$ref": "#/definitions/putUserspassword"
                        }, 
                        "required": false, 
                        "name": "body", 
                        "in": "body"
                    }
                ], 
                "summary": "Change user password"
            }
        }, 
        "/API/v1/api/users/?login_id=": {
            "delete": {
                "responses": {
                    "200": {
                        "description": "200 response", 
                        "examples": {}
                    }
                }, 
                "parameters": [], 
                "summary": "Delete user"
            }
        }
    }
}